// Code generated by MockGen. DO NOT EDIT.
// Source: ../kafka/consumer.go
//
// Generated by this command:
//
//	mockgen -source=../kafka/consumer.go -destination=kafka/mock_batch_handler.go -package=kafkamock
//

// Package kafkamock is a generated GoMock package.
package kafkamock

import (
	context "context"
	reflect "reflect"

	kafka "github.com/segmentio/kafka-go"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchHandler is a mock of BatchHandler interface.
type MockBatchHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBatchHandlerMockRecorder
	isgomock struct{}
}

// MockBatchHandlerMockRecorder is the mock recorder for MockBatchHandler.
type MockBatchHandlerMockRecorder struct {
	mock *MockBatchHandler
}

// NewMockBatchHandler creates a new mock instance.
func NewMockBatchHandler(ctrl *gomock.Controller) *MockBatchHandler {
	mock := &MockBatchHandler{ctrl: ctrl}
	mock.recorder = &MockBatchHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchHandler) EXPECT() *MockBatchHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockBatchHandler) Handle(ctx context.Context, msgs []kafka.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockBatchHandlerMockRecorder) Handle(ctx, msgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockBatchHandler)(nil).Handle), ctx, msgs)
}

// HandleOne mocks base method.
func (m *MockBatchHandler) HandleOne(ctx context.Context, msg kafka.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleOne", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleOne indicates an expected call of HandleOne.
func (mr *MockBatchHandlerMockRecorder) HandleOne(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleOne", reflect.TypeOf((*MockBatchHandler)(nil).HandleOne), ctx, msg)
}
