// Code generated by MockGen. DO NOT EDIT.
// Source: ../kafka/producer.go
//
// Generated by this command:
//
//	mockgen -source=../kafka/producer.go -destination=kafka/mock_event_publisher.go -package=kafkamock
//

// Package kafkamock is a generated GoMock package.
package kafkamock

import (
	context "context"
	reflect "reflect"

	kafka "github.com/quangdangfit/easypay/internal/kafka"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// PublishPaymentConfirmed mocks base method.
func (m *MockEventPublisher) PublishPaymentConfirmed(ctx context.Context, event kafka.PaymentConfirmedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentConfirmed", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentConfirmed indicates an expected call of PublishPaymentConfirmed.
func (mr *MockEventPublisherMockRecorder) PublishPaymentConfirmed(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentConfirmed", reflect.TypeOf((*MockEventPublisher)(nil).PublishPaymentConfirmed), ctx, event)
}
