// Code generated by MockGen. DO NOT EDIT.
// Source: ../service/types.go
//
// Generated by this command:
//
//	mockgen -source=../service/types.go -destination=service/mock_types.go -package=svcmock
//

// Package svcmock is a generated GoMock package.
package svcmock

import (
	context "context"
	reflect "reflect"

	service "github.com/quangdangfit/easypay/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPayments is a mock of Payments interface.
type MockPayments struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentsMockRecorder
	isgomock struct{}
}

// MockPaymentsMockRecorder is the mock recorder for MockPayments.
type MockPaymentsMockRecorder struct {
	mock *MockPayments
}

// NewMockPayments creates a new mock instance.
func NewMockPayments(ctrl *gomock.Controller) *MockPayments {
	mock := &MockPayments{ctrl: ctrl}
	mock.recorder = &MockPaymentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayments) EXPECT() *MockPaymentsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPayments) Create(ctx context.Context, in service.CreatePaymentInput) (*service.CreatePaymentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*service.CreatePaymentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentsMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPayments)(nil).Create), ctx, in)
}

// MockWebhooks is a mock of Webhooks interface.
type MockWebhooks struct {
	ctrl     *gomock.Controller
	recorder *MockWebhooksMockRecorder
	isgomock struct{}
}

// MockWebhooksMockRecorder is the mock recorder for MockWebhooks.
type MockWebhooksMockRecorder struct {
	mock *MockWebhooks
}

// NewMockWebhooks creates a new mock instance.
func NewMockWebhooks(ctrl *gomock.Controller) *MockWebhooks {
	mock := &MockWebhooks{ctrl: ctrl}
	mock.recorder = &MockWebhooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhooks) EXPECT() *MockWebhooksMockRecorder {
	return m.recorder
}

// CreateRefund mocks base method.
func (m *MockWebhooks) CreateRefund(ctx context.Context, in service.RefundInput) (*service.RefundResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefund", ctx, in)
	ret0, _ := ret[0].(*service.RefundResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefund indicates an expected call of CreateRefund.
func (mr *MockWebhooksMockRecorder) CreateRefund(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefund", reflect.TypeOf((*MockWebhooks)(nil).CreateRefund), ctx, in)
}

// Process mocks base method.
func (m *MockWebhooks) Process(ctx context.Context, payload []byte, sigHeader string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, payload, sigHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockWebhooksMockRecorder) Process(ctx, payload, sigHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockWebhooks)(nil).Process), ctx, payload, sigHeader)
}

// MockCheckouts is a mock of Checkouts interface.
type MockCheckouts struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutsMockRecorder
	isgomock struct{}
}

// MockCheckoutsMockRecorder is the mock recorder for MockCheckouts.
type MockCheckoutsMockRecorder struct {
	mock *MockCheckouts
}

// NewMockCheckouts creates a new mock instance.
func NewMockCheckouts(ctrl *gomock.Controller) *MockCheckouts {
	mock := &MockCheckouts{ctrl: ctrl}
	mock.recorder = &MockCheckoutsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckouts) EXPECT() *MockCheckoutsMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockCheckouts) Resolve(ctx context.Context, merchantID, orderID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, merchantID, orderID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockCheckoutsMockRecorder) Resolve(ctx, merchantID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockCheckouts)(nil).Resolve), ctx, merchantID, orderID)
}

// MockReconciler is a mock of Reconciler interface.
type MockReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockReconcilerMockRecorder
	isgomock struct{}
}

// MockReconcilerMockRecorder is the mock recorder for MockReconciler.
type MockReconcilerMockRecorder struct {
	mock *MockReconciler
}

// NewMockReconciler creates a new mock instance.
func NewMockReconciler(ctrl *gomock.Controller) *MockReconciler {
	mock := &MockReconciler{ctrl: ctrl}
	mock.recorder = &MockReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciler) EXPECT() *MockReconcilerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockReconciler) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockReconcilerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockReconciler)(nil).Run), ctx)
}

// MockMerchants is a mock of Merchants interface.
type MockMerchants struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantsMockRecorder
	isgomock struct{}
}

// MockMerchantsMockRecorder is the mock recorder for MockMerchants.
type MockMerchantsMockRecorder struct {
	mock *MockMerchants
}

// NewMockMerchants creates a new mock instance.
func NewMockMerchants(ctrl *gomock.Controller) *MockMerchants {
	mock := &MockMerchants{ctrl: ctrl}
	mock.recorder = &MockMerchantsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchants) EXPECT() *MockMerchantsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMerchants) Create(ctx context.Context, in service.CreateMerchantInput) (*service.CreateMerchantResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*service.CreateMerchantResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMerchantsMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMerchants)(nil).Create), ctx, in)
}
