// Code generated by MockGen. DO NOT EDIT.
// Source: ../service/fraud_service.go
//
// Generated by this command:
//
//	mockgen -source=../service/fraud_service.go -destination=service/mock_fraud.go -package=svcmock
//

// Package svcmock is a generated GoMock package.
package svcmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFraudChecker is a mock of FraudChecker interface.
type MockFraudChecker struct {
	ctrl     *gomock.Controller
	recorder *MockFraudCheckerMockRecorder
	isgomock struct{}
}

// MockFraudCheckerMockRecorder is the mock recorder for MockFraudChecker.
type MockFraudCheckerMockRecorder struct {
	mock *MockFraudChecker
}

// NewMockFraudChecker creates a new mock instance.
func NewMockFraudChecker(ctrl *gomock.Controller) *MockFraudChecker {
	mock := &MockFraudChecker{ctrl: ctrl}
	mock.recorder = &MockFraudCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFraudChecker) EXPECT() *MockFraudCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockFraudChecker) Check(ctx context.Context, merchantID, userID string, amount int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, merchantID, userID, amount)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockFraudCheckerMockRecorder) Check(ctx, merchantID, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockFraudChecker)(nil).Check), ctx, merchantID, userID, amount)
}
