// Code generated by MockGen. DO NOT EDIT.
// Source: ../cache/idempotency.go
//
// Generated by this command:
//
//	mockgen -source=../cache/idempotency.go -destination=cache/mock_idempotency.go -package=cachemock
//

// Package cachemock is a generated GoMock package.
package cachemock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyChecker is a mock of IdempotencyChecker interface.
type MockIdempotencyChecker struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyCheckerMockRecorder
	isgomock struct{}
}

// MockIdempotencyCheckerMockRecorder is the mock recorder for MockIdempotencyChecker.
type MockIdempotencyCheckerMockRecorder struct {
	mock *MockIdempotencyChecker
}

// NewMockIdempotencyChecker creates a new mock instance.
func NewMockIdempotencyChecker(ctrl *gomock.Controller) *MockIdempotencyChecker {
	mock := &MockIdempotencyChecker{ctrl: ctrl}
	mock.recorder = &MockIdempotencyCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyChecker) EXPECT() *MockIdempotencyCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockIdempotencyChecker) Check(ctx context.Context, key string) (bool, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Check indicates an expected call of Check.
func (mr *MockIdempotencyCheckerMockRecorder) Check(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockIdempotencyChecker)(nil).Check), ctx, key)
}

// Set mocks base method.
func (m *MockIdempotencyChecker) Set(ctx context.Context, key string, response []byte, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, response, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockIdempotencyCheckerMockRecorder) Set(ctx, key, response, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIdempotencyChecker)(nil).Set), ctx, key, response, ttl)
}
