// Code generated by MockGen. DO NOT EDIT.
// Source: ../cache/url_cache.go
//
// Generated by this command:
//
//	mockgen -source=../cache/url_cache.go -destination=cache/mock_url_cache.go -package=cachemock
//

// Package cachemock is a generated GoMock package.
package cachemock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockURLCache is a mock of URLCache interface.
type MockURLCache struct {
	ctrl     *gomock.Controller
	recorder *MockURLCacheMockRecorder
	isgomock struct{}
}

// MockURLCacheMockRecorder is the mock recorder for MockURLCache.
type MockURLCacheMockRecorder struct {
	mock *MockURLCache
}

// NewMockURLCache creates a new mock instance.
func NewMockURLCache(ctrl *gomock.Controller) *MockURLCache {
	mock := &MockURLCache{ctrl: ctrl}
	mock.recorder = &MockURLCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLCache) EXPECT() *MockURLCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockURLCache) Get(orderID string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orderID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLCacheMockRecorder) Get(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLCache)(nil).Get), orderID)
}

// Invalidate mocks base method.
func (m *MockURLCache) Invalidate(orderID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Invalidate", orderID)
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockURLCacheMockRecorder) Invalidate(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockURLCache)(nil).Invalidate), orderID)
}

// Put mocks base method.
func (m *MockURLCache) Put(orderID, url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Put", orderID, url)
}

// Put indicates an expected call of Put.
func (mr *MockURLCacheMockRecorder) Put(orderID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockURLCache)(nil).Put), orderID, url)
}
