// Code generated by MockGen. DO NOT EDIT.
// Source: ../cache/order_pending.go
//
// Generated by this command:
//
//	mockgen -source=../cache/order_pending.go -destination=cache/mock_pending_order.go -package=cachemock
//

// Package cachemock is a generated GoMock package.
package cachemock

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/quangdangfit/easypay/internal/cache"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingOrderStore is a mock of PendingOrderStore interface.
type MockPendingOrderStore struct {
	ctrl     *gomock.Controller
	recorder *MockPendingOrderStoreMockRecorder
	isgomock struct{}
}

// MockPendingOrderStoreMockRecorder is the mock recorder for MockPendingOrderStore.
type MockPendingOrderStoreMockRecorder struct {
	mock *MockPendingOrderStore
}

// NewMockPendingOrderStore creates a new mock instance.
func NewMockPendingOrderStore(ctrl *gomock.Controller) *MockPendingOrderStore {
	mock := &MockPendingOrderStore{ctrl: ctrl}
	mock.recorder = &MockPendingOrderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingOrderStore) EXPECT() *MockPendingOrderStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPendingOrderStore) Get(ctx context.Context, orderID string) (*cache.PendingOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, orderID)
	ret0, _ := ret[0].(*cache.PendingOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPendingOrderStoreMockRecorder) Get(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPendingOrderStore)(nil).Get), ctx, orderID)
}

// Put mocks base method.
func (m *MockPendingOrderStore) Put(ctx context.Context, o *cache.PendingOrder, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, o, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockPendingOrderStoreMockRecorder) Put(ctx, o, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockPendingOrderStore)(nil).Put), ctx, o, ttl)
}
