// Code generated by MockGen. DO NOT EDIT.
// Source: ../cache/token_bucket.go
//
// Generated by this command:
//
//	mockgen -source=../cache/token_bucket.go -destination=cache/mock_token_bucket.go -package=cachemock
//

// Package cachemock is a generated GoMock package.
package cachemock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenBucket is a mock of TokenBucket interface.
type MockTokenBucket struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBucketMockRecorder
	isgomock struct{}
}

// MockTokenBucketMockRecorder is the mock recorder for MockTokenBucket.
type MockTokenBucketMockRecorder struct {
	mock *MockTokenBucket
}

// NewMockTokenBucket creates a new mock instance.
func NewMockTokenBucket(ctrl *gomock.Controller) *MockTokenBucket {
	mock := &MockTokenBucket{ctrl: ctrl}
	mock.recorder = &MockTokenBucketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBucket) EXPECT() *MockTokenBucketMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockTokenBucket) Allow(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockTokenBucketMockRecorder) Allow(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockTokenBucket)(nil).Allow), ctx)
}
