// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/order_repo.go
//
// Generated by this command:
//
//	mockgen -source=../repository/order_repo.go -destination=repo/mock_order_repo.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/quangdangfit/easypay/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockOrderRepository) Insert(ctx context.Context, o *domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockOrderRepositoryMockRecorder) Insert(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockOrderRepository)(nil).Insert), ctx, o)
}

// GetByTransactionID mocks base method.
func (m *MockOrderRepository) GetByTransactionID(ctx context.Context, merchantID, transactionID string) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionID", ctx, merchantID, transactionID)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionID indicates an expected call of GetByTransactionID.
func (mr *MockOrderRepositoryMockRecorder) GetByTransactionID(ctx, merchantID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionID", reflect.TypeOf((*MockOrderRepository)(nil).GetByTransactionID), ctx, merchantID, transactionID)
}

// GetByOrderID mocks base method.
func (m *MockOrderRepository) GetByOrderID(ctx context.Context, orderID string) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockOrderRepositoryMockRecorder) GetByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockOrderRepository)(nil).GetByOrderID), ctx, orderID)
}

// GetByPaymentIntentID mocks base method.
func (m *MockOrderRepository) GetByPaymentIntentID(ctx context.Context, pi string) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPaymentIntentID", ctx, pi)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPaymentIntentID indicates an expected call of GetByPaymentIntentID.
func (mr *MockOrderRepositoryMockRecorder) GetByPaymentIntentID(ctx, pi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPaymentIntentID", reflect.TypeOf((*MockOrderRepository)(nil).GetByPaymentIntentID), ctx, pi)
}

// GetPendingBefore mocks base method.
func (m *MockOrderRepository) GetPendingBefore(ctx context.Context, before time.Time, limit int) ([]*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingBefore", ctx, before, limit)
	ret0, _ := ret[0].([]*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingBefore indicates an expected call of GetPendingBefore.
func (mr *MockOrderRepositoryMockRecorder) GetPendingBefore(ctx, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingBefore", reflect.TypeOf((*MockOrderRepository)(nil).GetPendingBefore), ctx, before, limit)
}

// UpdateCheckout mocks base method.
func (m *MockOrderRepository) UpdateCheckout(ctx context.Context, orderID, stripeSessionID, stripePaymentIntentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCheckout", ctx, orderID, stripeSessionID, stripePaymentIntentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCheckout indicates an expected call of UpdateCheckout.
func (mr *MockOrderRepositoryMockRecorder) UpdateCheckout(ctx, orderID, stripeSessionID, stripePaymentIntentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCheckout", reflect.TypeOf((*MockOrderRepository)(nil).UpdateCheckout), ctx, orderID, stripeSessionID, stripePaymentIntentID)
}

// UpdateStatus mocks base method.
func (m *MockOrderRepository) UpdateStatus(ctx context.Context, orderID string, status domain.OrderStatus, stripePaymentIntentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, status, stripePaymentIntentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateStatus(ctx, orderID, status, stripePaymentIntentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateStatus), ctx, orderID, status, stripePaymentIntentID)
}

// Mockscanner is a mock of scanner interface.
type Mockscanner struct {
	ctrl     *gomock.Controller
	recorder *MockscannerMockRecorder
	isgomock struct{}
}

// MockscannerMockRecorder is the mock recorder for Mockscanner.
type MockscannerMockRecorder struct {
	mock *Mockscanner
}

// NewMockscanner creates a new mock instance.
func NewMockscanner(ctrl *gomock.Controller) *Mockscanner {
	mock := &Mockscanner{ctrl: ctrl}
	mock.recorder = &MockscannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockscanner) EXPECT() *MockscannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *Mockscanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockscannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*Mockscanner)(nil).Scan), dest...)
}
