// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/pending_tx_repo.go
//
// Generated by this command:
//
//	mockgen -source=../repository/pending_tx_repo.go -destination=repo/mock_pending_tx_repo.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	domain "github.com/quangdangfit/easypay/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingTxRepository is a mock of PendingTxRepository interface.
type MockPendingTxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPendingTxRepositoryMockRecorder
	isgomock struct{}
}

// MockPendingTxRepositoryMockRecorder is the mock recorder for MockPendingTxRepository.
type MockPendingTxRepositoryMockRecorder struct {
	mock *MockPendingTxRepository
}

// NewMockPendingTxRepository creates a new mock instance.
func NewMockPendingTxRepository(ctrl *gomock.Controller) *MockPendingTxRepository {
	mock := &MockPendingTxRepository{ctrl: ctrl}
	mock.recorder = &MockPendingTxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingTxRepository) EXPECT() *MockPendingTxRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPendingTxRepository) Create(ctx context.Context, tx *domain.PendingTx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPendingTxRepositoryMockRecorder) Create(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPendingTxRepository)(nil).Create), ctx, tx)
}

// GetByTxHash mocks base method.
func (m *MockPendingTxRepository) GetByTxHash(ctx context.Context, hash string) (*domain.PendingTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTxHash", ctx, hash)
	ret0, _ := ret[0].(*domain.PendingTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTxHash indicates an expected call of GetByTxHash.
func (mr *MockPendingTxRepositoryMockRecorder) GetByTxHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTxHash", reflect.TypeOf((*MockPendingTxRepository)(nil).GetByTxHash), ctx, hash)
}

// ListPendingByChain mocks base method.
func (m *MockPendingTxRepository) ListPendingByChain(ctx context.Context, chainID int64, limit int) ([]*domain.PendingTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingByChain", ctx, chainID, limit)
	ret0, _ := ret[0].([]*domain.PendingTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingByChain indicates an expected call of ListPendingByChain.
func (mr *MockPendingTxRepositoryMockRecorder) ListPendingByChain(ctx, chainID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingByChain", reflect.TypeOf((*MockPendingTxRepository)(nil).ListPendingByChain), ctx, chainID, limit)
}

// UpdateConfirmations mocks base method.
func (m *MockPendingTxRepository) UpdateConfirmations(ctx context.Context, hash string, confirmations uint64, status domain.PendingTxStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfirmations", ctx, hash, confirmations, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfirmations indicates an expected call of UpdateConfirmations.
func (mr *MockPendingTxRepositoryMockRecorder) UpdateConfirmations(ctx, hash, confirmations, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfirmations", reflect.TypeOf((*MockPendingTxRepository)(nil).UpdateConfirmations), ctx, hash, confirmations, status)
}
