// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/transaction_repo.go
//
// Generated by this command:
//
//	mockgen -source=../repository/transaction_repo.go -destination=repo/mock_transaction_repo.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/quangdangfit/easypay/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// GetByMerchantOrderID mocks base method.
func (m *MockTransactionRepository) GetByMerchantOrderID(ctx context.Context, shardIdx uint8, merchantID, orderID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMerchantOrderID", ctx, shardIdx, merchantID, orderID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMerchantOrderID indicates an expected call of GetByMerchantOrderID.
func (mr *MockTransactionRepositoryMockRecorder) GetByMerchantOrderID(ctx, shardIdx, merchantID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMerchantOrderID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByMerchantOrderID), ctx, shardIdx, merchantID, orderID)
}

// GetByOrderIDAny mocks base method.
func (m *MockTransactionRepository) GetByOrderIDAny(ctx context.Context, orderID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderIDAny", ctx, orderID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderIDAny indicates an expected call of GetByOrderIDAny.
func (mr *MockTransactionRepositoryMockRecorder) GetByOrderIDAny(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderIDAny", reflect.TypeOf((*MockTransactionRepository)(nil).GetByOrderIDAny), ctx, orderID)
}

// GetByPaymentIntentID mocks base method.
func (m *MockTransactionRepository) GetByPaymentIntentID(ctx context.Context, pi string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPaymentIntentID", ctx, pi)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPaymentIntentID indicates an expected call of GetByPaymentIntentID.
func (mr *MockTransactionRepositoryMockRecorder) GetByPaymentIntentID(ctx, pi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPaymentIntentID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByPaymentIntentID), ctx, pi)
}

// GetByTransactionID mocks base method.
func (m *MockTransactionRepository) GetByTransactionID(ctx context.Context, shardIdx uint8, merchantID, transactionID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionID", ctx, shardIdx, merchantID, transactionID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionID indicates an expected call of GetByTransactionID.
func (mr *MockTransactionRepositoryMockRecorder) GetByTransactionID(ctx, shardIdx, merchantID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByTransactionID), ctx, shardIdx, merchantID, transactionID)
}

// GetPendingBefore mocks base method.
func (m *MockTransactionRepository) GetPendingBefore(ctx context.Context, before time.Time, limit int) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingBefore", ctx, before, limit)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingBefore indicates an expected call of GetPendingBefore.
func (mr *MockTransactionRepositoryMockRecorder) GetPendingBefore(ctx, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingBefore", reflect.TypeOf((*MockTransactionRepository)(nil).GetPendingBefore), ctx, before, limit)
}

// Insert mocks base method.
func (m *MockTransactionRepository) Insert(ctx context.Context, t *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockTransactionRepositoryMockRecorder) Insert(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTransactionRepository)(nil).Insert), ctx, t)
}

// UpdateCheckout mocks base method.
func (m *MockTransactionRepository) UpdateCheckout(ctx context.Context, shardIdx uint8, merchantID, orderID, stripeSessionID, stripePaymentIntentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCheckout", ctx, shardIdx, merchantID, orderID, stripeSessionID, stripePaymentIntentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCheckout indicates an expected call of UpdateCheckout.
func (mr *MockTransactionRepositoryMockRecorder) UpdateCheckout(ctx, shardIdx, merchantID, orderID, stripeSessionID, stripePaymentIntentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCheckout", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateCheckout), ctx, shardIdx, merchantID, orderID, stripeSessionID, stripePaymentIntentID)
}

// UpdateStatus mocks base method.
func (m *MockTransactionRepository) UpdateStatus(ctx context.Context, shardIdx uint8, merchantID, orderID string, status domain.TransactionStatus, stripePaymentIntentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, shardIdx, merchantID, orderID, status, stripePaymentIntentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTransactionRepositoryMockRecorder) UpdateStatus(ctx, shardIdx, merchantID, orderID, status, stripePaymentIntentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateStatus), ctx, shardIdx, merchantID, orderID, status, stripePaymentIntentID)
}

// Mockscanner is a mock of scanner interface.
type Mockscanner struct {
	ctrl     *gomock.Controller
	recorder *MockscannerMockRecorder
	isgomock struct{}
}

// MockscannerMockRecorder is the mock recorder for Mockscanner.
type MockscannerMockRecorder struct {
	mock *Mockscanner
}

// NewMockscanner creates a new mock instance.
func NewMockscanner(ctrl *gomock.Controller) *Mockscanner {
	mock := &Mockscanner{ctrl: ctrl}
	mock.recorder = &MockscannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockscanner) EXPECT() *MockscannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *Mockscanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockscannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*Mockscanner)(nil).Scan), dest...)
}
