// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/merchant_repo.go
//
// Generated by this command:
//
//	mockgen -source=../repository/merchant_repo.go -destination=repo/mock_merchant_repo.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	domain "github.com/quangdangfit/easypay/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMerchantRepository is a mock of MerchantRepository interface.
type MockMerchantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantRepositoryMockRecorder
	isgomock struct{}
}

// MockMerchantRepositoryMockRecorder is the mock recorder for MockMerchantRepository.
type MockMerchantRepositoryMockRecorder struct {
	mock *MockMerchantRepository
}

// NewMockMerchantRepository creates a new mock instance.
func NewMockMerchantRepository(ctrl *gomock.Controller) *MockMerchantRepository {
	mock := &MockMerchantRepository{ctrl: ctrl}
	mock.recorder = &MockMerchantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantRepository) EXPECT() *MockMerchantRepositoryMockRecorder {
	return m.recorder
}

// GetByAPIKey mocks base method.
func (m *MockMerchantRepository) GetByAPIKey(ctx context.Context, apiKey string) (*domain.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAPIKey", ctx, apiKey)
	ret0, _ := ret[0].(*domain.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAPIKey indicates an expected call of GetByAPIKey.
func (mr *MockMerchantRepositoryMockRecorder) GetByAPIKey(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAPIKey", reflect.TypeOf((*MockMerchantRepository)(nil).GetByAPIKey), ctx, apiKey)
}
