// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/onchain_tx_repo.go
//
// Generated by this command:
//
//	mockgen -source=../repository/onchain_tx_repo.go -destination=repo/mock_onchain_tx_repo.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	domain "github.com/quangdangfit/easypay/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOnchainTxRepository is a mock of OnchainTxRepository interface.
type MockOnchainTxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOnchainTxRepositoryMockRecorder
	isgomock struct{}
}

// MockOnchainTxRepositoryMockRecorder is the mock recorder for MockOnchainTxRepository.
type MockOnchainTxRepositoryMockRecorder struct {
	mock *MockOnchainTxRepository
}

// NewMockOnchainTxRepository creates a new mock instance.
func NewMockOnchainTxRepository(ctrl *gomock.Controller) *MockOnchainTxRepository {
	mock := &MockOnchainTxRepository{ctrl: ctrl}
	mock.recorder = &MockOnchainTxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnchainTxRepository) EXPECT() *MockOnchainTxRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOnchainTxRepository) Create(ctx context.Context, tx *domain.OnchainTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOnchainTxRepositoryMockRecorder) Create(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOnchainTxRepository)(nil).Create), ctx, tx)
}

// GetByTxHash mocks base method.
func (m *MockOnchainTxRepository) GetByTxHash(ctx context.Context, hash string) (*domain.OnchainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTxHash", ctx, hash)
	ret0, _ := ret[0].(*domain.OnchainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTxHash indicates an expected call of GetByTxHash.
func (mr *MockOnchainTxRepositoryMockRecorder) GetByTxHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTxHash", reflect.TypeOf((*MockOnchainTxRepository)(nil).GetByTxHash), ctx, hash)
}

// ListPendingByChain mocks base method.
func (m *MockOnchainTxRepository) ListPendingByChain(ctx context.Context, chainID int64, limit int) ([]*domain.OnchainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingByChain", ctx, chainID, limit)
	ret0, _ := ret[0].([]*domain.OnchainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingByChain indicates an expected call of ListPendingByChain.
func (mr *MockOnchainTxRepositoryMockRecorder) ListPendingByChain(ctx, chainID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingByChain", reflect.TypeOf((*MockOnchainTxRepository)(nil).ListPendingByChain), ctx, chainID, limit)
}

// UpdateConfirmations mocks base method.
func (m *MockOnchainTxRepository) UpdateConfirmations(ctx context.Context, hash string, confirmations uint64, status domain.OnchainTxStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfirmations", ctx, hash, confirmations, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfirmations indicates an expected call of UpdateConfirmations.
func (mr *MockOnchainTxRepositoryMockRecorder) UpdateConfirmations(ctx, hash, confirmations, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfirmations", reflect.TypeOf((*MockOnchainTxRepository)(nil).UpdateConfirmations), ctx, hash, confirmations, status)
}
