// Code generated by MockGen. DO NOT EDIT.
// Source: ../provider/stripe/client.go
//
// Generated by this command:
//
//	mockgen -source=../provider/stripe/client.go -destination=stripe/mock_client.go -package=stripemock
//

// Package stripemock is a generated GoMock package.
package stripemock

import (
	context "context"
	reflect "reflect"

	stripe "github.com/quangdangfit/easypay/internal/provider/stripe"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateCheckoutSession mocks base method.
func (m *MockClient) CreateCheckoutSession(ctx context.Context, req stripe.CreateCheckoutRequest, idempotencyKey string) (*stripe.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", ctx, req, idempotencyKey)
	ret0, _ := ret[0].(*stripe.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockClientMockRecorder) CreateCheckoutSession(ctx, req, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockClient)(nil).CreateCheckoutSession), ctx, req, idempotencyKey)
}

// CreatePaymentIntent mocks base method.
func (m *MockClient) CreatePaymentIntent(ctx context.Context, req stripe.CreatePaymentIntentRequest, idempotencyKey string) (*stripe.PaymentIntent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentIntent", ctx, req, idempotencyKey)
	ret0, _ := ret[0].(*stripe.PaymentIntent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentIntent indicates an expected call of CreatePaymentIntent.
func (mr *MockClientMockRecorder) CreatePaymentIntent(ctx, req, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentIntent", reflect.TypeOf((*MockClient)(nil).CreatePaymentIntent), ctx, req, idempotencyKey)
}

// CreateRefund mocks base method.
func (m *MockClient) CreateRefund(ctx context.Context, req stripe.CreateRefundRequest, idempotencyKey string) (*stripe.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefund", ctx, req, idempotencyKey)
	ret0, _ := ret[0].(*stripe.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefund indicates an expected call of CreateRefund.
func (mr *MockClientMockRecorder) CreateRefund(ctx, req, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefund", reflect.TypeOf((*MockClient)(nil).CreateRefund), ctx, req, idempotencyKey)
}

// GetCheckoutSession mocks base method.
func (m *MockClient) GetCheckoutSession(ctx context.Context, id string) (*stripe.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckoutSession", ctx, id)
	ret0, _ := ret[0].(*stripe.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckoutSession indicates an expected call of GetCheckoutSession.
func (mr *MockClientMockRecorder) GetCheckoutSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckoutSession", reflect.TypeOf((*MockClient)(nil).GetCheckoutSession), ctx, id)
}

// GetPaymentIntent mocks base method.
func (m *MockClient) GetPaymentIntent(ctx context.Context, id string) (*stripe.PaymentIntent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentIntent", ctx, id)
	ret0, _ := ret[0].(*stripe.PaymentIntent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentIntent indicates an expected call of GetPaymentIntent.
func (mr *MockClientMockRecorder) GetPaymentIntent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentIntent", reflect.TypeOf((*MockClient)(nil).GetPaymentIntent), ctx, id)
}

// VerifyWebhookSignature mocks base method.
func (m *MockClient) VerifyWebhookSignature(payload []byte, sigHeader, secret string) (*stripe.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhookSignature", payload, sigHeader, secret)
	ret0, _ := ret[0].(*stripe.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyWebhookSignature indicates an expected call of VerifyWebhookSignature.
func (mr *MockClientMockRecorder) VerifyWebhookSignature(payload, sigHeader, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhookSignature", reflect.TypeOf((*MockClient)(nil).VerifyWebhookSignature), payload, sigHeader, secret)
}
