// Code generated by MockGen. DO NOT EDIT.
// Source: ../provider/blockchain/cursor.go
//
// Generated by this command:
//
//	mockgen -source=../provider/blockchain/cursor.go -destination=blockchain/mock_cursor_store.go -package=bcmock
//

// Package bcmock is a generated GoMock package.
package bcmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCursorStore is a mock of CursorStore interface.
type MockCursorStore struct {
	ctrl     *gomock.Controller
	recorder *MockCursorStoreMockRecorder
	isgomock struct{}
}

// MockCursorStoreMockRecorder is the mock recorder for MockCursorStore.
type MockCursorStoreMockRecorder struct {
	mock *MockCursorStore
}

// NewMockCursorStore creates a new mock instance.
func NewMockCursorStore(ctrl *gomock.Controller) *MockCursorStore {
	mock := &MockCursorStore{ctrl: ctrl}
	mock.recorder = &MockCursorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCursorStore) EXPECT() *MockCursorStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCursorStore) Get(ctx context.Context, chainID int64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, chainID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCursorStoreMockRecorder) Get(ctx, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCursorStore)(nil).Get), ctx, chainID)
}

// Set mocks base method.
func (m *MockCursorStore) Set(ctx context.Context, chainID int64, block uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, chainID, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCursorStoreMockRecorder) Set(ctx, chainID, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCursorStore)(nil).Set), ctx, chainID, block)
}
